apiVersion: v1
kind: Service
metadata:
  labels:
    service: person-rpc
  name: person-rpc
spec:
  ports:
  - name: "50051"
    port: 50051
    targetPort: 50051
  selector:
    service: person-rpc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: person-rpc
  name: person-rpc
spec:
  replicas: 1
  selector:
    matchLabels:
      service: person-api
  template:
    metadata:
      labels:
        service: person-api
    spec:
      containers:
      - image: kydq2022/nd064-c2-person-rpc:latest
        name: person-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
