openapi: 3.1.0
info:
  title: "UdaConnect API"
  version: "0.1.0"
paths:
  /api/persons/{person_id}/connection:
    get:
      tags:
        - UdaConnect
      operationId: get_connection_data_resource
      parameters:
        - name: person_id
          in: path
          required: true
          schema:
            type: string
        - name: distance
          in: query
          description: Proximity to a given user in meters
          schema:
            type: string
        - name: end_date
          in: query
          description: Upper bound of date range
          schema:
            type: string
        - name: start_date
          in: query
          description: Lower bound of date range
          schema:
            type: string
      responses:
        '200':
          description: Success

  /api/persons:
    post:
      tags:
        - UdaConnect
      operationId: create_person
      requestBody:
        description: Person data to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request

  /api/locations:
    post:
      tags:
        - UdaConnect
      operationId: create_location
      requestBody:
        description: Location data to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Location'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request

components:
  schemas:
    Person:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        company_name:
          type: string

    Location:
      type: object
      properties:
        latitude:
          type: number
        longitude:
          type: number

  responses:
    ParseError:
      description: When a mask can't be parsed
    MaskError:
      description: When any error occurs on mask
